openapi: '3.0.2'
info:
  title: Tool Endpoint
  version: '1.0'
servers:
  - url: http://localhost:9999

paths:
  /tool:
    get:
      summary: Retrieve all tools
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  tools:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tool'
    post:
      summary: Create a new Tool
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tool'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tool'
        '422':
          description: Unprocessable entity

  /tools/{id}:
    get:
      summary: Retrieve a Tool by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the Tool to retrieve
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tool'
        '404':
          description: Tool not found

    put:
      summary: Update a Tool by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the Tool to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tool'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tool'
        '400':
          description: Bad request
        '422':
          description: Unprocessable entity
        '404':
          description: Tool not found

    delete:
      summary: Delete a Tool by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the Tool to delete
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Tool not found

components:
  schemas:
    Tool:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        link: 
          type: string
      required:
        - title
        - description
        - link
        - tags

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
